apiVersion: v1
kind: ReplicationController
metadata:
  name: myapp-rc
  labels:
    app: myapp
spec:
  template:
    metadata:
      name: myapp-pod
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx
  replicas: 3
